#!/usr/bin/bash

#Hi! If you're curious, this is a bash file. It's made to be run on bash, the "shell" (the thing that turns command lines into machine instructions) of Linux.
#If you're on Windows, try running "run.bat" instead.
#So yeah, I'm sorry, --import is a linux exclusive... though you can run "python ./src/import.py <url>" as an alternative.

cd "$(dirname "$(realpath "$0")")"

if [ $# -eq 0 ]
  then
    python ./index.py
elif [ "$1" == "--import" ]
  then
    echo "Attempting to import $2..."
    python ./src/import.py $2
elif [ "$1" == "editor" ]
  then
    python ./index.py editor
elif [ "$1" == "update" ]
  then
    read -p "Do you want to update shellrhythm? [Y/n]: " yn
    case $yn in
        [Yy]*) git pull origin main ;;  
        [Nn]*) echo "Update aborted." ;;
    esac
elif [ "$1" == "help" ]
  then
    echo "Welcome to shellrhythm!"
    echo ""
    echo "   shellrhythm            Starts the game."
    echo "   shellrhythm editor     Opens up the editor."
    echo "   shellrhythm --import   Imports an online chart."
    echo "   shellrhythm update     Checks for updates, then updates the game."
fi