#!/usr/bin/bash

#Hi! If you're curious, this is a bash file. It's made to be run on bash, the "shell" (the thing that turns command lines into machine code) of Linux.
#If you're on windows, try running "run.bat" instead.
python ./index.py